# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' applyItersplits
#' 
#' generate splits for splithalf
#'
#' @param iters number of iterations
#' @param splits list of vectors of row numbers
#' @export
applyItersplits <- function(iters, splits) {
    .Call('_rapidsplit_applyItersplits', PACKAGE = 'rapidsplit', iters, splits)
}

