# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' colMedians
#' 
#' get column medians
#'
#' @param mat the matrix to retrieve column medians from
#' @export
colMedians <- function(mat) {
    .Call('_rapidsplit_colMedians', PACKAGE = 'rapidsplit', mat)
}

#' @rdname colMedians
#' @param mat a matrix with values to aggregate
#' @param mask a logical matrix determining which data points to include and which not to
#' @export
colMedians_mask <- function(mat, mask) {
    .Call('_rapidsplit_colMedians_mask', PACKAGE = 'rapidsplit', mat, mask)
}

#' @rdname colMedians
#' @param values Values to aggregate over in different mask configurations
#' @export
mediansByMask <- function(values, mask) {
    .Call('_rapidsplit_mediansByMask', PACKAGE = 'rapidsplit', values, mask)
}

#' @rdname colMedians
#' @export
colMeans_mask <- function(mat, mask) {
    .Call('_rapidsplit_colMeans_mask', PACKAGE = 'rapidsplit', mat, mask)
}

#' @rdname colMedians
#' @param values Values to aggregate over in different mask configurations
#' @export
meansByMask <- function(values, mask) {
    .Call('_rapidsplit_meansByMask', PACKAGE = 'rapidsplit', values, mask)
}

#' colSds
#' 
#' get column SDs
#'
#' @param mat the matrix to retrieve column SDs from
#' @export
colSds <- function(mat) {
    .Call('_rapidsplit_colSds', PACKAGE = 'rapidsplit', mat)
}

#' @rdname colSds
#' @param mask a logical matrix determining which data points to include and which not to
#' @export
colSds_mask <- function(mat, mask) {
    .Call('_rapidsplit_colSds_mask', PACKAGE = 'rapidsplit', mat, mask)
}

#' @rdname colSds
#' @param values Values to aggregate over in different mask configurations
#' @export
sdsByMask <- function(values, mask) {
    .Call('_rapidsplit_sdsByMask', PACKAGE = 'rapidsplit', values, mask)
}

#' Exclude SD-based outliers
#' 
#' Update a mask matrix based on outlyingness
#' 
#' @param rtvec Reaction time vector
#' @param mask a logical matrix determining which data points to include and which not to
#' @param sdlim Standard deviation limit to apply; values beyond are classified as outliers and masked
#' @returns An updated mask
#' @export
ExcludeSDOutliers <- function(rtvec, mask, sdlim = 3) {
    .Call('_rapidsplit_ExcludeSDOutliers', PACKAGE = 'rapidsplit', rtvec, mask, sdlim)
}

#' @rdname ExcludeSDOutliers
#' @param mat Matrix in which to mark SD-based outleirs by column (with FALSE)
#' @export
ExcludeSDOutliers_nomask <- function(mat, sdlim = 3) {
    .Call('_rapidsplit_ExcludeSDOutliers_nomask', PACKAGE = 'rapidsplit', mat, sdlim)
}

#' applyItersplits
#' 
#' generate splits for splithalf
#'
#' @param iters number of iterations
#' @param splits list of vectors of row numbers
#' @param replace Sample without (default) or with replacement
#' @export
applyItersplits <- function(iters, splits, replace = FALSE) {
    .Call('_rapidsplit_applyItersplits', PACKAGE = 'rapidsplit', iters, splits, replace)
}

#' stratified_itersplits
#' 
#' generate stratified splits for a single participant
#' 
#' This first equally splits what can be equally split within groups.
#' Then it randomly splits all the leftovers.
#'
#' @param itercount number of iterations
#' @param groupsizes vector of number of RTs per group to stratify
#' @returns A matrix with zeroes and ones
#' @export
stratified_itersplits <- function(itercount, groupsizes) {
    .Call('_rapidsplit_stratified_itersplits', PACKAGE = 'rapidsplit', itercount, groupsizes)
}

#' Correlate each column of 1 matrix with the same column in another matrix
#' 
#' Correlate each column of 1 matrix with the same column in another matrix
#'
#' @param mat1,mat2 Matrices whose values to correlate by column
#' @returns A numeric vector of correlations per column
#' @export
corByColumns <- function(mat1, mat2) {
    .Call('_rapidsplit_corByColumns', PACKAGE = 'rapidsplit', mat1, mat2)
}

#' @rdname corByColumns
#' @param mask Logical matrix marking which data points to include
#' @export
corByColumns_mask <- function(mat1, mat2, mask) {
    .Call('_rapidsplit_corByColumns_mask', PACKAGE = 'rapidsplit', mat1, mat2, mask)
}

#' Exclude outliers by mask
#' 
#' Exclude outliers by mask
#'
#' @param values values to detect outliers from
#' @param mask a logical matrix determining which data points to include per iteration (column)
#' @params maxsd values exceeding more than this value in SDs will be excluded from the mask
#' @returns An updated logical mask matrix with all outliers excluded
#' @export
maskOLExclusion <- function(values, mask, maxsd) {
    .Call('_rapidsplit_maskOLExclusion', PACKAGE = 'rapidsplit', values, mask, maxsd)
}

